
hamiltonian:
  J_0: 0.025
  J_max: 0.100
  epsilon_0: 0.0
  alpha: 0.010

noise:
  sigma: 0.08
  gamma_range: [0.0001, 1.0]
  gamma_step:
    scale: log
    num: 60
  gamma_default: 0.02

sinks:
  k_sink: 0.20
  k_loss: 0.005

integration:
  dt: 0.2
  t_max: 60.0
